In [8]:
import numpy as np

path_pos = '../data/train_pos.npy'
path_neg = '../data/train_neg.npy'

In [9]:
try:
    # Load data from file .npy
    data_pos = np.load(path_pos)
    data_neg = np.load(path_neg)

    # --- Positive Data Information ---
    print("Positive Data (train_pos.npy):")
    # Display 5 first row
    print(data_pos[:5]) 
    # Displat data dimension (row and col count)
    print("Positive Data Dimension:", data_pos.shape)
    print("-" * 30)

    # --- Negative Data Information ---
    print("Negative Data (train_neg.npy):")
    # Display 5 first row
    print(data_neg[:5])
    # Display data dimension
    print("Negative Data Dimension:", data_neg.shape)

except FileNotFoundError:
    print("Error: File not found.")

Positive Data (train_pos.npy):
[[   0 1113    1]
 [   0  736    1]
 [   0  888    1]
 [   0  636    1]
 [   1  374    1]]
Positive Data Dimension: (26638, 3)
------------------------------
Negative Data (train_neg.npy):
[[   0   87    0]
 [   0 1791    0]
 [   0  587    0]
 [   0  100    0]
 [   1  680    0]]
Negative Data Dimension: (24037, 3)
